# GENES
AGE_DEAD = 'AGE_DEAD'
AGE_BORN_CHILD = 'AGE_BORN_CHILD'
INVEST = 'INVEST'
SAVE_MONEY = 'SAVE_MONEY'
CREDIT = 'CREDIT'
SEX = 'SEX'
MARRIAGE = 'MARRIAGE'
STUDY = 'STUDY'
DEAD_CAUSE_NATURAL = 'NATURAL'
DEAD_CAUSE_CANT_PROVIDE_BASIC_NEEDS = 'CANT_PROVIDE_BASIC_NEEDS'

